import { useEffect, useMemo, useState } from 'react';
import { Alert, Box, Button, Card, CardActionArea, CardContent, Chip, FormControl, Grid, InputLabel, Link, MenuItem, Paper, Select, Stack, TextField, Typography } from '@mui/material';
import type { FieldSchema, FormSchema } from '@dynamic-forms/core';
import { FormProvider, useFormContext } from '@dynamic-forms/react';
import { createDefaultMuiRegistry, MuiFieldLoading, MuiFieldRenderer } from '@dynamic-forms/mui';
import { controlCatalog, createCatalogField, defaultCatalogValue, type ControlFamily, type ControlStatus } from '../../config/controlCatalog';
const registry = createDefaultMuiRegistry();
const families = ['all','Input','Selection','Date/time','Numeric','File/media','Nested'] as const;
const statuses = ['all','stable','beta','experimental'] as const;
function SeedError({ name }: { name: string }) { const { store } = useFormContext(); useEffect(() => { store.setError(name, 'Example validation error'); }, [name, store]); return null; }
function Variant({ title, field, error = false }: { title: string; field: FieldSchema; error?: boolean }) {
  const schema: FormSchema = { id: `catalog-${field.name}-${title}`, fields: [field] }; const initial = { [field.name]: defaultCatalogValue(field.type) };
  if (!registry[field.type]) return <Paper variant="outlined" sx={{ p: 2 }}><Typography variant="subtitle2">{title}</Typography><Alert severity="warning">Schema-only type; no default MUI renderer.</Alert></Paper>;
  if (field.type === 'hidden') return <Paper variant="outlined" sx={{ p: 2 }}><Typography variant="subtitle2">{title}</Typography><Alert severity="info">Hidden controls intentionally produce no visible UI.</Alert></Paper>;
  return <Paper variant="outlined" sx={{ p: 2, minHeight: 150 }}><Typography variant="subtitle2">{title}</Typography><FormProvider schema={schema} defaultValues={initial}>{error && <SeedError name={field.name} />}<MuiFieldRenderer field={field} registry={registry} /></FormProvider></Paper>;
}
export default function Fields() {
  const [search, setSearch] = useState(''); const [family, setFamily] = useState<(typeof families)[number]>('all'); const [status, setStatus] = useState<(typeof statuses)[number]>('all'); const [selectedType, setSelectedType] = useState('text');
  const visible = useMemo(() => controlCatalog.filter((item) => (!search || item.type.includes(search.toLowerCase())) && (family === 'all' || item.family === family) && (status === 'all' || item.status === status)), [family, search, status]);
  const selected = controlCatalog.find((item) => item.type === selectedType) ?? controlCatalog[0]; const base = createCatalogField(selected.type);
  return <Stack spacing={4}><Box><Typography component="h1" variant="h3">All Fields catalogue</Typography><Typography color="text.secondary">{controlCatalog.filter((item) => item.registered).length} registered controls and {controlCatalog.filter((item) => !item.registered).length} schema-only capabilities.</Typography></Box>
    <Stack direction={{ xs: 'column', md: 'row' }} spacing={2}><TextField label="Search controls" value={search} onChange={(event) => setSearch(event.target.value)} /><FormControl sx={{ minWidth: 180 }}><InputLabel>Category</InputLabel><Select label="Category" value={family} onChange={(event) => setFamily(event.target.value as ControlFamily | 'all')}>{families.map((item) => <MenuItem key={item} value={item}>{item}</MenuItem>)}</Select></FormControl><FormControl sx={{ minWidth: 160 }}><InputLabel>Status</InputLabel><Select label="Status" value={status} onChange={(event) => setStatus(event.target.value as ControlStatus | 'all')}>{statuses.map((item) => <MenuItem key={item} value={item}>{item}</MenuItem>)}</Select></FormControl></Stack>
    <Grid container spacing={2}>{visible.map((item) => <Grid key={item.type} size={{ xs: 12, sm: 6, md: 4, xl: 3 }}><Card variant={selected.type === item.type ? 'elevation' : 'outlined'}><CardActionArea onClick={() => setSelectedType(item.type)}><CardContent><Stack direction="row" justifyContent="space-between"><Typography variant="h6">{item.type}</Typography><Chip size="small" label={item.status} color={item.status === 'stable' ? 'success' : item.status === 'beta' ? 'warning' : 'default'} /></Stack><Typography variant="body2">{item.family}</Typography><Typography variant="caption" color="text.secondary">{item.valueType}</Typography></CardContent></CardActionArea></Card></Grid>)}</Grid>
    {!visible.length && <Alert severity="info">No controls match the current filters.</Alert>}
    <Stack spacing={2}><Stack direction="row" spacing={1} alignItems="center"><Typography component="h2" variant="h4">{selected.type}</Typography><Chip label={selected.family} /><Chip label={selected.status} /></Stack><Typography>Value: <code>{selected.valueType}</code></Typography>{selected.advanced && <Alert severity="info">Keyboard: use Tab to focus, arrow keys to navigate choices or ranges, Enter/Space to select, and Escape to close popups.</Alert>}{selected.asyncStates && <Stack spacing={1}><Alert severity="info">Async coverage for controls that load remote options or files.</Alert><Grid container spacing={1}><Grid size={{ xs: 12, sm: 4 }}><Paper variant="outlined" sx={{ p: 2 }}><Typography variant="subtitle2">Loading</Typography><MuiFieldLoading label="Loading catalogue data" /></Paper></Grid><Grid size={{ xs: 12, sm: 4 }}><Alert severity="info">Empty: no options available.</Alert></Grid><Grid size={{ xs: 12, sm: 4 }}><Alert severity="error" action={<Button size="small">Retry</Button>}>Failure: request unavailable.</Alert></Grid></Grid></Stack>}<Grid container spacing={2}><Grid size={{ xs: 12, md: 6 }}><Variant title="Normal" field={base} /></Grid><Grid size={{ xs: 12, md: 6 }}><Variant title="Disabled" field={createCatalogField(selected.type, { disabled: true })} /></Grid><Grid size={{ xs: 12, md: 6 }}><Variant title="Read-only" field={createCatalogField(selected.type, { readOnly: true })} /></Grid><Grid size={{ xs: 12, md: 6 }}><Variant title="Required" field={createCatalogField(selected.type, { validation: { required: true } })} /></Grid><Grid size={{ xs: 12, md: 6 }}><Variant title="Error" field={base} error /></Grid></Grid><Paper component="pre" variant="outlined" sx={{ p: 2, overflow: 'auto' }} aria-label="Schema snippet">{JSON.stringify(base, null, 2)}</Paper><Button component={Link} href={`/docs/CONTROL#registered-controls`}>Open control documentation</Button></Stack>
  </Stack>;
}
