import { useState } from 'react';
import type { FormSchema } from '@dynamic-form-engine/core';
import { FormProvider } from '@dynamic-form-engine/react';
import { HtmlForm } from '@dynamic-form-engine/react-html';
export function Preview({ schema, errors, submitted, onSubmitted, viewport, setViewport, density, setDensity, scheme, setScheme }: { schema: FormSchema; errors: readonly { path: string; message: string }[]; submitted?: Readonly<Record<string, unknown>>; onSubmitted: (values?: Readonly<Record<string, unknown>>) => void; viewport: 'desktop'|'tablet'|'mobile'; setViewport: (value: 'desktop'|'tablet'|'mobile') => void; density: 'compact'|'standard'|'comfortable'; setDensity: (value: 'compact'|'standard'|'comfortable') => void; scheme: 'light'|'dark'|'auto'; setScheme: (value: 'light'|'dark'|'auto') => void }) {
  const [run, setRun] = useState(0);
  return <main className="preview-view"><div className="preview-toolbar"><div>{(['desktop','tablet','mobile'] as const).map((item) => <button key={item} className={viewport === item ? 'active' : ''} onClick={() => setViewport(item)}>{item}</button>)}</div><label>Density <select value={density} onChange={(event) => setDensity(event.target.value as typeof density)}><option>compact</option><option>standard</option><option>comfortable</option></select></label><label>Theme <select value={scheme} onChange={(event) => setScheme(event.target.value as typeof scheme)}><option>light</option><option>dark</option><option>auto</option></select></label><button onClick={() => { setRun((value) => value + 1); onSubmitted(undefined); }}>Reset preview</button></div>{errors.length ? <div className="preview-errors" role="alert"><h2>Preview unavailable</h2><p>Resolve schema errors before rendering.</p><ul>{errors.map((error, index) => <li key={index}>{error.path}: {error.message}</li>)}</ul></div> : <div className={`preview-frame ${viewport}`}><div className="preview-card"><p className="eyebrow">Live preview</p><h1>{humanize(schema.id)}</h1><FormProvider key={`${JSON.stringify(schema)}-${run}`} schema={schema} onError={() => undefined}><HtmlForm schema={schema} density={density} colorScheme={scheme} submitLabel="Submit form" onSubmit={(values) => onSubmitted(values)} /></FormProvider>{submitted ? <section className="submitted"><h2>Submitted values</h2><pre>{JSON.stringify(submitted, null, 2)}</pre></section> : null}</div></div>}</main>;
}
function humanize(value: string) { return value.replace(/[-_]/g, ' ').replace(/([a-z])([A-Z])/g, '$1 $2').replace(/^./, (char) => char.toUpperCase()) || 'Untitled form'; }
