import { useMemo, useState } from 'react';
import { FormStore, type FormSchema } from '@dynamic-form-engine/core';
import { FormProvider } from '@dynamic-form-engine/react';
import { HtmlForm } from '@dynamic-form-engine/react-html';
import type { WizardConfig } from '../builder/wizard';
export function Preview({ schema, wizard, errors, submitted, onSubmitted, viewport, setViewport, density, setDensity, scheme, setScheme }: { schema: FormSchema; wizard:WizardConfig; errors: readonly { path: string; message: string }[]; submitted?: Readonly<Record<string, unknown>>; onSubmitted: (values?: Readonly<Record<string, unknown>>) => void; viewport: 'desktop'|'tablet'|'mobile'; setViewport: (value: 'desktop'|'tablet'|'mobile') => void; density: 'compact'|'standard'|'comfortable'; setDensity: (value: 'compact'|'standard'|'comfortable') => void; scheme: 'light'|'dark'|'auto'; setScheme: (value: 'light'|'dark'|'auto') => void }) {
 const [run,setRun]=useState(0);const [index,setIndex]=useState(0);const [visited,setVisited]=useState<readonly number[]>([]);const [invalid,setInvalid]=useState<readonly number[]>([]);const [values,setValues]=useState<Readonly<Record<string,unknown>>>({});
 const store=useMemo(()=>new FormStore<Record<string,unknown>>(),[schema.id,run]);const step=wizard.steps[Math.min(index,wizard.steps.length-1)];const wizardMode=wizard.mode==='wizard';const stepFields=step?.review?[]:schema.fields.filter(f=>!wizardMode||step?.fieldPaths.includes(f.name));const stepSchema={...schema,fields:stepFields};
 const advance=(nextValues:Readonly<Record<string,unknown>>)=>{setValues(nextValues);setInvalid(items=>items.filter(i=>i!==index));setVisited(items=>items.includes(index)?items:[...items,index]);if(index<wizard.steps.length-1)setIndex(index+1);else onSubmitted(nextValues)};
 return <main className="preview-view"><div className="preview-toolbar"><div>{(['desktop','tablet','mobile'] as const).map(item=><button key={item} className={viewport===item?'active':''} onClick={()=>setViewport(item)}>{item}</button>)}</div><label>Density <select value={density} onChange={e=>setDensity(e.target.value as typeof density)}><option>compact</option><option>standard</option><option>comfortable</option></select></label><label>Theme <select value={scheme} onChange={e=>setScheme(e.target.value as typeof scheme)}><option>light</option><option>dark</option><option>auto</option></select></label><button onClick={()=>{setRun(v=>v+1);setIndex(0);setVisited([]);setInvalid([]);setValues({});onSubmitted(undefined)}}>Reset preview</button></div>{errors.length?<div className="preview-errors" role="alert"><h2>Preview unavailable</h2><p>Resolve schema errors before rendering.</p><ul>{errors.map((e,i)=><li key={i}>{e.path}: {e.message}</li>)}</ul></div>:<div className={`preview-frame ${viewport}`}><div className="preview-card"><p className="eyebrow">Live preview</p><h1>{humanize(schema.id)}</h1>{wizardMode?<ol className="preview-steps" aria-label="Form progress">{wizard.steps.map((s,i)=><li key={s.id} className={i===index?'active':invalid.includes(i)?'invalid':visited.includes(i)?'complete':''}><span>{s.icon||i+1}</span>{s.title}{s.optional?<small>Optional</small>:null}</li>)}</ol>:null}<FormProvider key={run} store={store} schema={stepSchema} onError={()=>undefined} onInvalidSubmit={()=>setInvalid(items=>items.includes(index)?items:[...items,index])} focusOnInvalidSubmit><HtmlForm schema={stepSchema} density={density} colorScheme={scheme} submitLabel={wizardMode&&index<wizard.steps.length-1?'Next':'Submit form'} onSubmit={advance}>{wizardMode&&index>0?<button type="button" className="wizard-previous" onClick={()=>setIndex(index-1)}>Previous</button>:null}{step?.review?<section className="wizard-review"><h2>{step.title}</h2><p>{step.description}</p><pre>{JSON.stringify(values,null,2)}</pre></section>:null}</HtmlForm></FormProvider>{submitted?<section className="submitted"><h2>Submitted values</h2><pre>{JSON.stringify(submitted,null,2)}</pre></section>:null}</div></div>}</main>;
}
function humanize(value:string){return value.replace(/[-_]/g,' ').replace(/([a-z])([A-Z])/g,'$1 $2').replace(/^./,c=>c.toUpperCase())||'Untitled form'}
