import type { FormSchema } from '@dynamic-form-engine/core';
import { Button, IconButton, Switch } from '../../ui/Primitives';
import { addWizardStep, duplicateWizardStep, moveFieldToStep, moveWizardStep, removeWizardStep, updateWizardStep, type WizardConfig } from '../wizard';
export function WizardDesigner({schema,config,activeId,onChange,onActive}:{schema:FormSchema;config:WizardConfig;activeId:string;onChange:(value:WizardConfig)=>void;onActive:(id:string)=>void}) {
 const active=config.steps.find(s=>s.id===activeId)??config.steps[0];
 return <section className={`wizard-designer wizard-designer--${config.mode}`} aria-label="Form steps">
  <div className="wizard-mode"><strong>Form flow</strong><label>Mode <select value={config.mode} onChange={e=>onChange({...config,mode:e.target.value as WizardConfig['mode']})}><option value="single">Single page</option><option value="wizard">Wizard</option></select></label>{config.mode==='wizard'?<label>Validate <select value={config.validationPolicy} onChange={e=>onChange({...config,validationPolicy:e.target.value as WizardConfig['validationPolicy']})}><option value="onNext">Each step</option><option value="onSubmit">On submit</option></select></label>:null}</div>
  {config.mode==='wizard'?<><div className="wizard-stepper" role="tablist" aria-label="Wizard steps">{config.steps.map((s,i)=><button role="tab" aria-selected={s.id===active.id} className={s.id===active.id?'active':''} key={s.id} onClick={()=>onActive(s.id)}><span>{i+1}</span><b>{s.title}</b>{s.optional?<small>Optional</small>:null}{s.review?<small>Review</small>:null}</button>)}<Button size="small" onClick={()=>{const next=addWizardStep(config);onChange(next);onActive(next.steps.at(-1)!.id)}}>+ Step</Button></div>
  <div className="wizard-step-editor"><label>Title<input aria-label="Step title" value={active.title} onChange={e=>onChange(updateWizardStep(config,active.id,{title:e.target.value}))}/></label><label>Description<input aria-label="Step description" value={active.description??''} onChange={e=>onChange(updateWizardStep(config,active.id,{description:e.target.value||undefined}))}/></label><label>Icon<input aria-label="Step icon" value={active.icon??''} placeholder="e.g. user" onChange={e=>onChange(updateWizardStep(config,active.id,{icon:e.target.value||undefined}))}/></label><Switch label="Optional" checked={active.optional??false} onChange={e=>onChange(updateWizardStep(config,active.id,{optional:e.target.checked}))}/><Switch label="Review step" checked={active.review??false} onChange={e=>onChange(updateWizardStep(config,active.id,{review:e.target.checked}))}/><IconButton aria-label="Move step left" disabled={config.steps[0].id===active.id} onClick={()=>onChange(moveWizardStep(config,active.id,-1))}>Move</IconButton><IconButton aria-label="Move step right" disabled={config.steps.at(-1)!.id===active.id} onClick={()=>onChange(moveWizardStep(config,active.id,1))}>Move</IconButton><Button size="small" onClick={()=>onChange(duplicateWizardStep(config,active.id))}>Duplicate</Button><Button size="small" variant="ghost" disabled={config.steps.length===1} onClick={()=>{if(!confirm('Delete this step? Its fields will move to the first step.'))return;const next=removeWizardStep(config,active.id);onChange(next);onActive(next.steps[0].id)}}>Delete</Button></div>
  <div className="wizard-field-map">{schema.fields.map(field=><label key={field.name}>{field.label??field.name}<select aria-label={`Move ${field.label??field.name} to step`} value={config.steps.find(s=>s.fieldPaths.includes(field.name))?.id??config.steps[0].id} onChange={e=>onChange(moveFieldToStep(config,field.name,e.target.value))}>{config.steps.filter(s=>!s.review).map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select></label>)}</div></>:null}
 </section>;
}
