import { useEffect, useState, type DragEvent, type ReactNode } from 'react';
import type { ConditionOperator, DataSourceConfig, FieldCondition, FieldSchema, FieldType, FormSchema } from '@dynamic-form-engine/core';
import { hasOptions, isNumeric, isTextual, palette } from '../schema/catalogue';
import { allPaths, fieldsAt, findField, normalizeType, structural } from '../schema/operations';
export function Palette({ onAdd }: { onAdd: (type: FieldType) => void }) {
  const groups = [...new Set(palette.map((item) => item.group))];
  return <aside className="palette-panel"><h2>Fields</h2><p>Drag or click to add</p>{groups.map((group) => <section key={group}><h3>{group}</h3><div className="palette-grid">{palette.filter((item) => item.group === group).map((item) => <button key={item.type} aria-label={item.label} draggable onDragStart={(event) => event.dataTransfer.setData('application/x-builder-field', item.type)} onClick={() => onAdd(item.type)}><span aria-hidden="true">{item.label.slice(0, 2)}</span>{item.label}</button>)}</div></section>)}</aside>;
}

interface NodeProps {
  field: FieldSchema; path: string; selectedPath?: string;
  onSelect: (path: string) => void; onAdd: (type: FieldType, parentPath?: string) => void; onDrop: (event: DragEvent, parentPath: string) => void;
  onMove: (path: string, direction: -1 | 1) => void; onReparent: (path: string, parent: string) => void;
  onDuplicate: (path: string) => void; onRemove: (path: string) => void;
}
export function FieldNode(props: NodeProps) {
  const { field, path } = props; const parentPath = path.split('.').slice(0, -1).join('.');
  return <div className="node-wrap" role="treeitem" aria-selected={props.selectedPath === path}>
    <article className={props.selectedPath === path ? 'field-node selected' : 'field-node'} onClick={() => props.onSelect(path)} draggable onDragStart={(event) => { event.stopPropagation(); event.dataTransfer.setData('application/x-builder-path', path); }}>
      <button className="handle" aria-label={`Select ${field.label ?? field.name}`}>:</button>
      <div className="field-summary"><strong>{field.label ?? field.name}{field.validation?.required ? ' *' : ''}</strong><small>{field.type} / {path}</small><div className="badges">{field.visibleWhen || field.disabledWhen || field.requiredWhen ? <span>conditional</span> : null}{field.dependsOn?.length ? <span>dependent</span> : null}{field.dataSource ? <span>data</span> : null}</div></div>
      <div className="node-actions"><button title="Move up" aria-label="Move up" onClick={(event) => { event.stopPropagation(); props.onMove(path, -1); }}>Up</button><button title="Move down" aria-label="Move down" onClick={(event) => { event.stopPropagation(); props.onMove(path, 1); }}>Down</button>{parentPath ? <button title="Move to root" onClick={(event) => { event.stopPropagation(); props.onReparent(path, ''); }}>Out</button> : null}<button title="Duplicate" onClick={(event) => { event.stopPropagation(); props.onDuplicate(path); }}>Copy</button><button className="danger" title="Delete" onClick={(event) => { event.stopPropagation(); props.onRemove(path); }}>Delete</button></div>
    </article>
    {structural(field) ? <div className="children" role="group">{field.fields?.map((child) => <FieldNode {...props} key={child.name} field={child} path={`${path}.${child.name}`} />)}<DropZone label={`Add child to ${field.label ?? field.name}`} onAdd={() => props.onAdd('text', path)} onDrop={(event) => props.onDrop(event, path)} /></div> : null}
  </div>;
}
export function DropZone({ label, onAdd, onDrop }: { label: string; onAdd: () => void; onDrop: (event: DragEvent) => void }) {
  return <button className="drop-zone" onClick={onAdd} onDragOver={(event) => event.preventDefault()} onDrop={onDrop}>{label}</button>;
}

interface InspectorProps { schema: FormSchema; path?: string; field?: FieldSchema; errors: readonly { message: string }[]; onPatch: (patch: Partial<FieldSchema>) => void; onReparent: (parent: string) => void }
export function Inspector({ schema, path, field, errors, onPatch, onReparent }: InspectorProps) {
  const [metadata, setMetadata] = useState(''); const [config, setConfig] = useState('');
  useEffect(() => { setMetadata(field?.metadata ? JSON.stringify(field.metadata, null, 2) : ''); setConfig(field?.config ? JSON.stringify(field.config, null, 2) : ''); }, [field?.config, field?.metadata, path]);
  if (!field) return <aside className="inspector"><h2>Properties</h2><p>Select a field to edit it.</p></aside>;
  const parent = path?.split('.').slice(0, -1).join('.') ?? ''; const siblings = fieldsAt(schema, parent);
  const patchJson = (key: 'metadata' | 'config', text: string) => { try { onPatch({ [key]: text.trim() ? JSON.parse(text) : undefined }); } catch { /* retain working text */ } };
  return <aside className="inspector"><div className="inspector-heading"><h2>Properties</h2><span>{field.type}</span></div>{errors.map((error) => <p className="field-error" key={error.message}>{error.message}</p>)}<div className="property-list">
    <Section title="General" open><Control label="Label"><input value={field.label ?? ''} onChange={(event) => onPatch({ label: event.target.value })} /></Control><Control label="Name"><input value={field.name} onChange={(event) => onPatch({ name: safeName(event.target.value) })} /></Control><Control label="Type"><select value={field.type} onChange={(event) => onPatch(normalizeType(field, event.target.value))}>{palette.map((item) => <option key={item.type} value={item.type}>{item.label}</option>)}</select></Control><Control label="Description"><textarea rows={2} value={field.description ?? ''} onChange={(event) => onPatch({ description: event.target.value || undefined })} /></Control><Control label="Placeholder"><input value={field.placeholder ?? ''} onChange={(event) => onPatch({ placeholder: event.target.value || undefined })} /></Control><Control label="Default value"><input value={typeof field.defaultValue === 'string' || typeof field.defaultValue === 'number' ? String(field.defaultValue) : ''} onChange={(event) => onPatch({ defaultValue: event.target.value || undefined })} /></Control><Toggle label="Disabled" checked={field.disabled ?? false} onChange={(disabled) => onPatch({ disabled })} /><Toggle label="Read only" checked={field.readOnly ?? false} onChange={(readOnly) => onPatch({ readOnly })} /></Section>
    <Section title="Validation"><Toggle label="Required" checked={field.validation?.required ?? false} onChange={(required) => onPatch({ validation: { ...field.validation, required } })} />{isTextual(field.type) ? <><NumberControl label="Minimum length" value={field.validation?.minLength} onChange={(minLength) => onPatch({ validation: { ...field.validation, minLength } })} /><NumberControl label="Maximum length" value={field.validation?.maxLength} onChange={(maxLength) => onPatch({ validation: { ...field.validation, maxLength } })} /><Control label="Pattern"><input value={field.validation?.pattern ?? ''} onChange={(event) => onPatch({ validation: { ...field.validation, pattern: event.target.value || undefined } })} /></Control></> : null}{isNumeric(field.type) ? <><NumberControl label="Minimum" value={field.validation?.min} onChange={(min) => onPatch({ validation: { ...field.validation, min } })} /><NumberControl label="Maximum" value={field.validation?.max} onChange={(max) => onPatch({ validation: { ...field.validation, max } })} /></> : null}{field.type === 'array' ? <><NumberControl label="Minimum items" value={field.validation?.minItems} onChange={(minItems) => onPatch({ validation: { ...field.validation, minItems } })} /><NumberControl label="Maximum items" value={field.validation?.maxItems} onChange={(maxItems) => onPatch({ validation: { ...field.validation, maxItems } })} /></> : null}</Section>
    {hasOptions(field.type) ? <Section title="Options" open><OptionEditor field={field} onPatch={onPatch} /></Section> : null}
    <Section title="Conditions & dependencies"><ConditionEditor label="Visible when" condition={field.visibleWhen} paths={allPaths(schema).filter((item) => item !== path)} onChange={(visibleWhen) => onPatch({ visibleWhen })} /><ConditionEditor label="Disabled when" condition={field.disabledWhen} paths={allPaths(schema).filter((item) => item !== path)} onChange={(disabledWhen) => onPatch({ disabledWhen })} /><ConditionEditor label="Required when" condition={field.requiredWhen} paths={allPaths(schema).filter((item) => item !== path)} onChange={(requiredWhen) => onPatch({ requiredWhen })} /><Control label="Dependencies (comma-separated)"><input value={field.dependsOn?.join(', ') ?? ''} onChange={(event) => onPatch({ dependsOn: event.target.value.split(',').map((item) => item.trim()).filter(Boolean) })} /></Control><Toggle label="Reset on dependency change" checked={field.resetOnDependencyChange ?? false} onChange={(resetOnDependencyChange) => onPatch({ resetOnDependencyChange })} /><Control label="Hidden value policy"><select value={field.hiddenValuePolicy ?? 'preserve'} onChange={(event) => onPatch({ hiddenValuePolicy: event.target.value as FieldSchema['hiddenValuePolicy'] })}><option value="preserve">Preserve</option><option value="clear">Clear</option><option value="reset">Reset</option></select></Control></Section>
    {hasOptions(field.type) ? <Section title="Data source"><DataSourceEditor value={field.dataSource} onChange={(dataSource) => onPatch({ dataSource })} /></Section> : null}
    <Section title="Structure"><Control label="Parent"><select value={parent} onChange={(event) => onReparent(event.target.value)}><option value="">Form root</option>{allPaths(schema).filter((candidate) => candidate !== path && !candidate.startsWith(`${path}.`) && structural(findField(schema, candidate)!.field)).map((candidate) => <option key={candidate} value={candidate}>{candidate}</option>)}</select></Control></Section>
    <Section title="Advanced"><Control label="Metadata JSON"><textarea rows={5} value={metadata} onChange={(event) => setMetadata(event.target.value)} onBlur={() => patchJson('metadata', metadata)} /></Control><Control label="Type config JSON"><textarea rows={5} value={config} onChange={(event) => setConfig(event.target.value)} onBlur={() => patchJson('config', config)} /></Control>{field.dataSource?.type === 'function' ? <p className="notice">Function data sources are preserved but cannot be edited or executed.</p> : null}<p className="muted">{siblings.length} sibling field{siblings.length === 1 ? '' : 's'}</p></Section>
  </div></aside>;
}

function Section({ title, children, open = false }: { title: string; children: ReactNode; open?: boolean }) { return <details open={open}><summary>{title}</summary><div className="section-body">{children}</div></details>; }
function Control({ label, children }: { label: string; children: ReactNode }) { return <label className="control-label"><span>{label}</span>{children}</label>; }
function Toggle({ label, checked, onChange }: { label: string; checked: boolean; onChange: (value: boolean) => void }) { return <label className="toggle"><span>{label}</span><input type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} /></label>; }
function NumberControl({ label, value, onChange }: { label: string; value?: number; onChange: (value?: number) => void }) { return <Control label={label}><input type="number" value={value ?? ''} onChange={(event) => onChange(event.target.value === '' ? undefined : Number(event.target.value))} /></Control>; }

function OptionEditor({ field, onPatch }: { field: FieldSchema; onPatch: (patch: Partial<FieldSchema>) => void }) {
  const options = [...(field.options ?? [])];
  const update = (index: number, patch: Record<string, unknown>) => { options[index] = { ...options[index], ...patch }; onPatch({ options }); };
  return <div className="options">{options.map((option, index) => <div className="option-row" key={index}><input aria-label={`Option ${index + 1} label`} value={option.label} onChange={(event) => update(index, { label: event.target.value })} /><input aria-label={`Option ${index + 1} value`} value={String(option.value)} onChange={(event) => update(index, { value: event.target.value })} /><button aria-label="Move option up" disabled={!index} onClick={() => { [options[index - 1], options[index]] = [options[index], options[index - 1]]; onPatch({ options }); }}>Up</button><button aria-label="Delete option" onClick={() => onPatch({ options: options.filter((_, item) => item !== index) })}>X</button></div>)}<button onClick={() => onPatch({ options: [...options, { label: 'New option', value: `option${options.length + 1}` }] })}>Add option</button></div>;
}

const operators: readonly ConditionOperator[] = ['equals','notEquals','exists','notExists','contains','greaterThan','lessThan'];
function ConditionEditor({ label, condition, paths, onChange }: { label: string; condition?: FieldCondition; paths: string[]; onChange: (value?: FieldCondition) => void }) {
  const simple = condition && 'field' in condition ? condition : undefined;
  return <fieldset className="condition"><legend>{label}</legend><Toggle label="Enabled" checked={Boolean(condition)} onChange={(enabled) => onChange(enabled ? { field: paths[0] ?? '', operator: 'equals', value: '' } : undefined)} />{condition ? <><select aria-label={`${label} field`} value={simple?.field ?? ''} onChange={(event) => onChange({ field: event.target.value, operator: simple?.operator ?? 'equals', value: simple?.value })}><option value="">Select field</option>{paths.map((path) => <option key={path}>{path}</option>)}</select><select aria-label={`${label} operator`} value={simple?.operator ?? 'equals'} onChange={(event) => onChange({ field: simple?.field ?? '', operator: event.target.value as ConditionOperator, value: simple?.value })}>{operators.map((operator) => <option key={operator}>{operator}</option>)}</select><input aria-label={`${label} value`} value={String(simple?.value ?? '')} onChange={(event) => onChange({ field: simple?.field ?? '', operator: simple?.operator ?? 'equals', value: event.target.value })} /><small>Nested and/or/not groups remain editable in JSON view.</small></> : null}</fieldset>;
}

function DataSourceEditor({ value, onChange }: { value?: DataSourceConfig; onChange: (value?: DataSourceConfig) => void }) {
  const type = value?.type ?? 'none';
  return <div className="data-source"><Control label="Source type"><select value={type} onChange={(event) => { const next = event.target.value; onChange(next === 'none' ? undefined : next === 'static' ? { type: 'static', options: [] } : { type: 'url', url: '', method: 'GET' }); }}><option value="none">Schema options</option><option value="static">Static</option><option value="url">URL</option>{type === 'function' ? <option value="function">Function (read-only)</option> : null}</select></Control>{type === 'static' ? <Control label="Static options JSON"><textarea rows={4} value={JSON.stringify(value?.options ?? [], null, 2)} onChange={(event) => { try { onChange({ ...value, type: 'static', options: JSON.parse(event.target.value) }); } catch { /* wait for valid JSON */ } }} /></Control> : null}{type === 'url' ? <><Control label="URL"><input value={value?.url ?? ''} onChange={(event) => onChange({ ...value, type: 'url', url: event.target.value })} /></Control><Control label="Method"><select value={value?.method ?? 'GET'} onChange={(event) => onChange({ ...value, type: 'url', method: event.target.value as 'GET' | 'POST' })}><option>GET</option><option>POST</option></select></Control><Control label="Search parameter"><input value={value?.searchParam ?? ''} onChange={(event) => onChange({ ...value, type: 'url', searchParam: event.target.value || undefined })} /></Control><Toggle label="Cache results" checked={value?.cache ?? false} onChange={(cache) => onChange({ ...value, type: 'url', cache })} /></> : null}</div>;
}



function safeName(value: string) { return value.replace(/[^a-zA-Z0-9]+(.)?/g, (_, char: string | undefined) => char?.toUpperCase() ?? '').replace(/^[A-Z]/, (char) => char.toLowerCase()); }
