import { useEffect, useState } from 'react';
import { Alert, Button, FormControl, InputLabel, MenuItem, Paper, Select, Stack, Typography } from '@mui/material';
import { FormErrorSummary, useFormActions, useFormContext, useFormState, useWatch, type ValidationMode } from '@dynamic-forms/react';
import DemoShell from '../../components/DemoShell/DemoShell';
import { validationInitialValues, validationSchema } from '@dynamic-forms/examples/validation';
import { validationSource } from '../../examples/validation/ValidationExample';
function ValidationTools() {
  const username = useWatch<string>('username') ?? ''; const age = useWatch<number | ''>('age'); const password = useWatch<string>('password') ?? ''; const confirm = useWatch<string>('confirmPassword') ?? ''; const errors = useFormState((state) => state.errors); const actions = useFormActions(); const { store } = useFormContext(); const [asyncState, setAsyncState] = useState('Idle'); const [trace, setTrace] = useState<string[]>([]);
  useEffect(() => { if (username.length < 3) { setAsyncState('Idle'); return; } const controller = new AbortController(); setAsyncState('Debouncing'); const debounce = window.setTimeout(() => { if (controller.signal.aborted) return; setAsyncState('Checking'); const request = window.setTimeout(() => { if (controller.signal.aborted) return; if (username.toLowerCase() === 'admin') { store.setError('username', 'Username is already in use'); setAsyncState('Unavailable'); } else { if (errors.username === 'Username is already in use') store.clearError('username'); setAsyncState('Available'); } }, 150); controller.signal.addEventListener('abort', () => window.clearTimeout(request), { once: true }); }, 350); return () => { controller.abort(); window.clearTimeout(debounce); }; }, [errors.username, store, username]);
  const custom = () => { if (username.toLowerCase() === 'root') actions.setError('username', 'Username root is reserved'); else if (errors.username === 'Username root is reserved') actions.clearError('username'); if (password && confirm && password !== confirm) actions.setError('confirmPassword', 'Passwords must match'); else if (errors.confirmPassword === 'Passwords must match') actions.clearError('confirmPassword'); };
  const timedValidation = async () => { const started = performance.now(); const valid = await actions.validateForm(); setTrace((current) => [`Validation completed in ${(performance.now()-started).toFixed(2)} ms (${valid ? 'valid' : 'invalid'})`, ...current].slice(0, 8)); };
  return <Stack spacing={2}><FormErrorSummary focusOnChange={false} /><Stack direction={{ xs: 'column', sm: 'row' }} spacing={1}><Button onClick={custom}>Run custom validation</Button><Button onClick={() => actions.setError('email', 'Server rejected this email address')}>Simulate server error</Button><Button onClick={() => void timedValidation()}>Measure validation</Button></Stack><Alert severity={asyncState === 'Unavailable' ? 'error' : 'info'}>Async username: {asyncState} (debounced and cancellable)</Alert>{typeof age === 'number' && age >= 18 && age < 21 && <Alert severity="warning">Applicants under 21 may require additional review. This warning does not block submission.</Alert>}<Paper variant="outlined" sx={{ p: 2 }}><Typography variant="subtitle2">Validation timing trace</Typography>{trace.length ? trace.map((item) => <div key={item}>{item}</div>) : <Typography variant="body2">No measurements yet.</Typography>}</Paper></Stack>;
}
export default function Validation() { const [mode, setMode] = useState<ValidationMode>('onBlur'); return <Stack spacing={2}><FormControl sx={{ width: 240 }}><InputLabel>Validation mode</InputLabel><Select label="Validation mode" value={mode} onChange={(event) => setMode(event.target.value as ValidationMode)}><MenuItem value="onChange">Change</MenuItem><MenuItem value="onBlur">Blur</MenuItem><MenuItem value="onSubmit">Submit</MenuItem></Select></FormControl><DemoShell key={mode} metadata={{ title: 'Validation laboratory', purpose: 'Compare schema, custom, cross-field, async, server, warning, and error behavior.', difficulty: 'advanced', packages: ['@dynamic-forms/core','@dynamic-forms/react','@dynamic-forms/mui'], expectedBehavior: ['Empty submission shows a summary and focuses Username.', 'Schema constraints respect the selected validation mode.', 'Custom validation rejects root and mismatched passwords.', 'Admin triggers cancellable debounced validation.', 'Warnings do not block submission.'] }} schema={validationSchema} defaultValues={validationInitialValues} source={validationSource} validationMode={mode} runtimeAddon={<ValidationTools />} /></Stack>; }
