import { createDefaultMuiRegistry } from '@dynamic-forms/mui';
import { Alert, Button, Card, CardContent, Chip, Grid, LinearProgress, Link, Paper, Stack, Table, TableBody, TableCell, TableHead, TableRow, Typography } from '@mui/material';
import { buildSnapshot, capabilityMatrix, packageStatuses, qualitySnapshot, recentChanges } from '../../config/dashboard';
const controlCounts = [{ label: 'Stable registered', value: Object.keys(createDefaultMuiRegistry()).length }, { label: 'Beta', value: 0 }, { label: 'Planned/schema-only', value: 4 }];
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <Stack spacing={2}><Typography variant="h5" component="h2">{title}</Typography>{children}</Stack>; }
export default function Dashboard() {
  const budgetUsage = Math.round((buildSnapshot.mainKb / buildSnapshot.budgetKb) * 100);
  return <Stack spacing={5}>
    <Stack spacing={1}><Typography variant="h3" component="h1">Enterprise playground</Typography><Typography color="text.secondary">Executable examples, transparent maturity, and reproducible engineering evidence.</Typography><Stack direction="row" spacing={1}><Button variant="contained" href="/basic-form">Start the basic form</Button><Button href="/docs/getting-started/quick-start">Read quick start</Button></Stack></Stack>
    <Section title="Package and build status"><Grid container spacing={2}>{packageStatuses.map((item) => <Grid key={item.name} size={{ xs: 12, sm: 6, xl: 3 }}><Card variant="outlined" sx={{ height: '100%' }}><CardContent><Chip size="small" label={item.status} color={item.status === 'Implemented' ? 'success' : 'default'} /><Typography variant="h6" sx={{ mt: 1 }}>{item.name}</Typography><Typography variant="body2" color="text.secondary">{item.responsibility}</Typography></CardContent></Card></Grid>)}</Grid></Section>
    <Section title="Control maturity"><Grid container spacing={2}>{controlCounts.map((item) => <Grid key={item.label} size={{ xs: 12, sm: 4 }}><Paper variant="outlined" sx={{ p: 2 }}><Chip size="small" label={item.label} /><Typography variant="h3" sx={{ mt: 1 }}>{item.value}</Typography></Paper></Grid>)}</Grid><Typography variant="caption" color="text.secondary">Derived from the default MUI registry and Core schema-only types. Registered does not imply release-ready documentation.</Typography></Section>
    <Section title="Core capability matrix"><Paper variant="outlined"><Table size="small"><TableHead><TableRow><TableCell>Capability</TableCell><TableCell>Core</TableCell><TableCell>React</TableCell><TableCell>MUI</TableCell></TableRow></TableHead><TableBody>{capabilityMatrix.map((row) => <TableRow key={row.capability}><TableCell>{row.capability}</TableCell>{(['core','react','mui'] as const).map((key) => <TableCell key={key}>{row[key] ? 'Yes' : 'No'}</TableCell>)}</TableRow>)}</TableBody></Table></Paper></Section>
    <Grid container spacing={3}><Grid size={{ xs: 12, lg: 6 }}><Section title="Bundle-size summary"><Paper variant="outlined" sx={{ p: 2 }}><Typography>Main shell: {buildSnapshot.mainKb} kB / {buildSnapshot.budgetKb} kB budget</Typography><LinearProgress variant="determinate" value={budgetUsage} color="success" sx={{ my: 1 }} /><Typography variant="body2">Shared MUI: {buildSnapshot.sharedMuiKb} kB · DemoShell: {buildSnapshot.demoShellKb} kB · Basic Form entry: {buildSnapshot.basicFormKb} kB · Quickstart entry: {buildSnapshot.quickstartKb} kB</Typography><Typography variant="caption">{buildSnapshot.source}; verified {buildSnapshot.verified}.</Typography></Paper></Section></Grid><Grid size={{ xs: 12, lg: 6 }}><Section title="Accessibility, tests, and benchmark"><Paper variant="outlined"><Table size="small"><TableBody>{qualitySnapshot.map((item) => <TableRow key={item.check}><TableCell>{item.check}</TableCell><TableCell><Chip size="small" label={item.result} color={item.result.includes('Passing') || item.result.includes('passing') ? 'success' : 'default'} /></TableCell><TableCell>{item.evidence}</TableCell></TableRow>)}</TableBody></Table></Paper></Section></Grid></Grid>
    <Section title="Recent examples and release notes"><Grid container spacing={2}>{recentChanges.map((item) => <Grid key={item.title} size={{ xs: 12, md: 4 }}><Card variant="outlined"><CardContent><Typography variant="h6">{item.title}</Typography><Typography variant="body2" color="text.secondary">{item.detail}</Typography></CardContent></Card></Grid>)}</Grid></Section>
    <Section title="Architecture overview"><Alert severity="info">Core owns portable behavior; React owns subscriptions and lifecycle; MUI owns visual controls; the playground composes them without leaking demo concerns into packages.</Alert><Stack direction={{ xs: 'column', sm: 'row' }} spacing={2}><Link href="/basic-form">Runnable Basic Form</Link><Link href="/docs/CONTROL">Control inventory</Link><Link href="https://github.com/lourthuxavierm/dynamic-forms" target="_blank" rel="noreferrer">Repository history</Link></Stack></Section>
  </Stack>;
}
