import type { MuiFieldRegistry } from './types';

import {
  MuiTextField,
  MuiTextarea,
  MuiPasswordField,
  MuiEmailField,
  MuiUrlField,
  MuiNumberField,
  MuiIntegerField,
  MuiDecimalField,
  MuiHiddenField,
  MuiSelect,
  MuiMultiSelect,
  MuiAutocomplete,
  MuiAsyncAutocomplete,
  MuiCheckbox,
  MuiCheckboxGroup,
  MuiRadio,
  MuiRadioGroup,
  MuiSwitch,
  MuiToggleButtonGroup,
  MuiTreeSelect,
  MuiDateField,
  MuiTimeField,
  MuiDateTimeField,
  MuiDateRangeField,
  MuiTimeRangeField,
  MuiDateTimeRangeField,
  MuiMonthField,
  MuiYearField,
  MuiCurrencyField,
  MuiPercentageField,
  MuiSlider,
  MuiRangeSlider,
  MuiRating,
  MuiPhoneField,
  MuiOtpField,
  MuiPinField,
  MuiMaskField,
} from '../components';

export function createDefaultMuiRegistry(): MuiFieldRegistry {
  return {
    // Core
    text: MuiTextField,
    textarea: MuiTextarea,
    password: MuiPasswordField,
    email: MuiEmailField,
    url: MuiUrlField,
    number: MuiNumberField,
    integer: MuiIntegerField,
    decimal: MuiDecimalField,
    hidden: MuiHiddenField,

    // Selection
    select: MuiSelect,
    'multi-select': MuiMultiSelect,
    autocomplete: MuiAutocomplete,
    'async-autocomplete': MuiAsyncAutocomplete,
    checkbox: MuiCheckbox,
    'checkbox-group': MuiCheckboxGroup,
    radio: MuiRadio,
    'radio-group': MuiRadioGroup,
    switch: MuiSwitch,
    'toggle-button-group': MuiToggleButtonGroup,
    'tree-select': MuiTreeSelect,

    // Date / Time
    date: MuiDateField,
    time: MuiTimeField,
    datetime: MuiDateTimeField,
    'date-range': MuiDateRangeField,
    'time-range': MuiTimeRangeField,
    'datetime-range': MuiDateTimeRangeField,
    month: MuiMonthField,
    year: MuiYearField,

    // Specialized
    currency: MuiCurrencyField,
    percentage: MuiPercentageField,
    slider: MuiSlider,
    'range-slider': MuiRangeSlider,
    rating: MuiRating,
    phone: MuiPhoneField,
    otp: MuiOtpField,
    pin: MuiPinField,
    // mask: MuiMaskField,
  };
}
